reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: false
    labels: 
      - "request-code-rabbit-review "
    drafts: false
chat:
  auto_reply: true