[package]
name = "registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema =  { workspace = true }
cosmwasm-std =  { workspace = true }
osmosis-std-derive = "0.13.2"
serde-json-wasm = { workspace = true }
prost = {version = "0.11.2", default-features = false, features = ["prost-derive"]}
crosschain-registry = { path = "../../contracts/crosschain-registry", features = ["imported"]}
