name: "Auto Assign Reviewers"
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign reviewers based on modified files
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          configuration-path: ".github/auto_assign_reviewers_config.yml"
          token: "${{ secrets.GITHUB_TOKEN }}"
