name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: true
  pull_request:
    types:
      - labeled
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ChatGPT-review')
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: ChatGPT Code Review
        id: chatgpt_codereview
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PULL_REQUEST_NUMBER: ${{ github.event.inputs.pull_request_number || github.event.pull_request.number }}
          
      - name: Debug
        run: |
          echo "ChatGPT Code Review - Output:"
          echo "${{ steps.chatgpt_codereview.outputs }}"
