name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    if: >-
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'chat-gpt-review')) ||
      (github.event.action == 'labeled' && contains(github.event.label.name, 'chat-gpt-review'))

    steps:
      - name: ChatGPT Code Review
        id: chatgpt_codereview
        uses: mattverse/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}