name: Render and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    name: Render and deploy protocol and API docs
    timeout-minutes: 30
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Load Rust caching
        uses: astriaorg/buildjet-rust-cache@v2.5.1
      - name: Load get-version action to grab version component of deployment path
        uses: battila7/get-version-action@v2
        id: get_version
      - name: Print version component of deployment path
        run: echo ${{ steps.get_version.outputs.version }}
      - name: Install mdbook
        run: cargo install mdbook mdbook-katex mdbook-mermaid
      - name: Build protocol spec
        run: cd docs/protocol && mdbook build
      - name: Move protocol spec to subdirectory
        run: |
          cd docs/protocol
          if [ -d "do-tmp" ]; then rm -rf do-tmp; fi
          mkdir do-tmp
          mv book do-tmp/${{ steps.get_version.outputs.version }}
          tree do-tmp
      - name: Deploy protocol spec to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: osmosis-protocol
          PROJECT_PATH: docs/protocol
      - name: Deploy
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$DO_DOCS_PK" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $DO_DOCS_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r * root@$DO_DOCS_IP:/var/www/html
