# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * ibc-hooks
# is updated in local branch.
name: Go Mod auto version bump
on: [pull_request]

jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Current branch commit
        run: |
          echo $(git rev-parse $GITHUB_BASE_REF)

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run script 
        run: |
          bash ./scripts/update-go-mod.sh
          echo make_PR ${{ env.MAKE_PULL_REQUEST }}

      - name: Create pull request
        if: ${{ env.MAKE_PULL_REQUEST }} == 1
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ secrets.COMMIT_TO_BRANCH }}
          base: $GITHUB_HEAD_REF
          commit-message: go.mod update
          delete-branch: true
          branch: create-pull-request/upgrade-go-mod
          title: \`go.mod\` update
          body: Updated go.mod due to changes in osmoutils, osmomath or x/ibc-hooks on branch $GITHUB_HEAD_REF

      

          



