# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * ibc-hooks
# is updated in local branch.
name: Go Mod auto version bump
on: [push]
env:
  PULL_REQUEST_BOOL: 0

jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get current branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

      - name: Get diff
        run: |
          COMMIT_ON_REMOTE=$(git rev-parse `git branch -r --sort=committerdate | tail -1`)
          CHANGED_OSMOUTILS=$(git diff --name-only $COMMIT_ON_REMOTE HEAD | grep osmoutils)
          CHANGED_OSMOMATH=$(git diff --name-only $COMMIT_ON_REMOTE HEAD | grep osmomath)
          CHANGED_IBC_HOOKS=$(git diff --name-only $COMMIT_ON_REMOTE HEAD | grep x/ibc-hooks)

      - name: Run script 
        run: |
          bash scripts/update-go-mod.sh
          PULL_REQUEST_BOOL=$?

      - name: Create pool request
        if: $PULL_REQUEST_BOOL == 1
        uses: peter-evans/create-pull-request@v4
        with: 
          token: $CURRENT_BRANCH
          commit-message: go.mod update
          delete-branch: true
          base: $CURRENT_BRANCH
          title: \`go.mod\` update
          body: Updated go.mod due to changes in osmoutils, osmomath or x/ibc-hooks on branch $CURRENT_BRANCH

      

          



