# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * ibc-hooks
# is updated in local branch.
name: Go Mod auto version bump
on: [push]
jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get current branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo $CURRENT_BRANCH

      - name: Get diff
        run: |
          COMMIT_ON_REMOTE=$(git rev-parse `git branch -r --sort=committerdate | tail -1`)
          CHANGED_OSMOUTILS=$(git diff --name-only $COMMIT_ON_REMOTE HEAD | grep osmoutils)
          CHANGED_OSMOMATH=$(git diff --name-only $COMMIT_ON_REMOTE HEAD | grep osmomath)
          CHANGED_IBC_HOOKS=$(git diff --name-only $COMMIT_ON_REMOTE HEAD | grep x/ibc-hooks)

      - name: Run script 
        run: |
          



