# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * ibc-hooks
# is updated in local branch.
name: Go Mod auto version bump
on: [pull_request, workflow_dispatch]

jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get current branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo CURRENT_BRANCH

      - name: Run script 
        run: |
          scripts/update-go-mod.sh
          echo make_PR ${{ env.MAKE_PULL_REQUEST }}
          echo diff: $(git diff)
          echo current_branch: $CURRENT_BRANCH

      - name: Create pull request
        if: ${{ env.MAKE_PULL_REQUEST }} == 1
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ secrets.COMMIT_TO_BRANCH }}
          base: $CURRENT_BRANCH
          commit-message: go.mod update
          delete-branch: true
          branch: create-pull-request/upgrade-go-mod
          title: \`go.mod\` update
          body: Updated go.mod due to changes in osmoutils, osmomath or x/ibc-hooks on branch $CURRENT_BRANCH

      

          



