# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * ibc-hooks
# is updated in local branch.
name: Go Mod auto version bump
on: [push]

jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    env: 
      PULL_REQUEST_BOOL: 0
      COMMIT_ON_REMOTE: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get current branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

      - name: Run script 
        run: |
          bash scripts/update-go-mod.sh
          echo "env.PULL_REQUEST_BOOL=$?"

      - name: Create pool request
        if: ${{ env.PULL_REQUEST_BOOL }} == 1
        uses: peter-evans/create-pull-request@v4
        with: 
          token: $CURRENT_BRANCH
          commit-message: go.mod update
          delete-branch: true
          base: $CURRENT_BRANCH
          title: \`go.mod\` update
          body: Updated go.mod due to changes in osmoutils, osmomath or x/ibc-hooks on branch $CURRENT_BRANCH

      

          



