# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * ibc-hooks
# is updated in local branch.
name: Go Mod auto version bump
on: [pull_request, workflow_dispatch]

jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Branch name
        run: |
          echo GH_REF ${GITHUB_REF}
          echo GH_HEAD_REF ${GITHUB_HEAD_REF} ${{ github.head_ref }}
          echo GH_BASE_REF ${GITHUB_BASE_REF} ${{ github.base_ref }}


      - name: Run script 
        run: |
          bash ./scripts/update-go-mod.sh
          echo make_PR ${{ env.MAKE_PULL_REQUEST }}
          echo current_branch: ${{ env.CURRENT_BRANCH }}

      - name: Create pull request
        if: ${{ env.MAKE_PULL_REQUEST }} == 1
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ secrets.COMMIT_TO_BRANCH }}
          base: ${{ env.CURRENT_BRANCH }}
          commit-message: go.mod update
          delete-branch: true
          branch: create-pull-request/upgrade-go-mod
          title: \`go.mod\` update
          body: Updated go.mod due to changes in osmoutils, osmomath or x/ibc-hooks on branch ${{ env.CURRENT_BRANCH }}

      

          



