name: Validate Makefile

on:
  pull_request:
    branches:
      - main  # assuming your default branch is named "main"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v2
      with:
        # Fetch all history for all branches and tags so we can access everything needed for the comparison
        fetch-depth: 0

    # Step 2: Set up the environment for the script, in this case, it's likely to be a shell script so we might not need to install additional dependencies

    # Step 3: Check out the main branch Makefile
    - name: Check out main branch Makefile
      run: |
        # Fetch the main branch
        git fetch origin main:main
        # Check out the Makefile from the main branch
        git show main:Makefile > Makefile.main

    # Step 4: Run your validation script
    - name: Validate Makefile
      run: |
        # make the script executable
        chmod +x ./scripts/validate-makefile.sh
        # run the script with parameters
        ./scripts/validate-makefile.sh Makefile Makefile.main
