name: required labels

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "concentrated-liquidity-main"
      - "v[0-9]**"
  workflow_dispatch:

jobs:
  await_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for check suites to complete
        id: await-check-suites
        uses: jitterbit/await-check-suites@v1 # Use the correct version/tag
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          failStepIfUnsuccessful: "true"
      - name: Set PR to draft if checks failed
        if: steps.await-check-suites.outputs.conclusion != 'success'
        run: |
          gh pr update ${{ github.event.pull_request.number }} --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
