name: Weekly Docs Update

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "v[0-9]**"

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run make docs
      run: make docs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.COMMIT_TO_BRANCH }}
        commit-message: Update documentation
        title: 'Weekly Documentation Update'
        body: 'Updates the documentation.'
        branch: 'docs-update-${{ github.run_number }}'
        base: 'main'
        delete-branch: true
        draft: false
